name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.3
  dart_frog_web_socket: ^0.1.0-dev.3
  dart_jsonwebtoken: ^2.7.1
  dbcrypt: ^2.0.0
  mysql1: ^0.20.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
